enetc: tsn: Export enetc_pspeed_set() to fix module build
Fixes -
ERROR: "enetc_pspeed_set" [drivers/net/ethernet/freescale/enetc/fsl-enetc.ko] undefined!
scripts/Makefile.modpost:93: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
Makefile:1293: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:179: recipe for target 'sub-make' failed

Fixes: 95b33c0bbaec ("enetc: add support tsn capabilities qbv/qci/qbu/cbs")
Signed-off-by: Claudiu Manoil <claudiu.manoil@nxp.com>